name: 'Install cargo-prebuilt'
description: 'Install cargo prebuilt to a runner'
author: 'harmless-tech, crow-rest'
branding:
  icon: arrow-down-circle
  color: gray-dark
inputs:
  version:
    required: true
    description: 'Version of cargo-prebuilt to use'
    default: latest
  target:
    required: true
    description: 'Target for the version cargo-prebuilt to use'
    default: current
  always-install:
    description: 'If the current installed version of cargo-prebuilt should be overridden'
    default: 'false'
outputs:
  version:
    description: 'version that was installed'
  target:
    description: 'target that was installed'
runs:
  using: 'node16'
  main: 'dist/index.js'
